Docb009 - user's crud
DOCQC/REPS-BACKEND pull request #13
Opened 2023-11-22 22:12 UTC by Wilker345

2023-11-23 23:10 UTC, SaldanhaElisson requested changes

2023-11-23 23:10 UTC, SaldanhaElisson commented on src/middlewares/exceptions/errorHandler.js
Alguns erros, como por exemplo quando o Id do user_type_id do CRUD user está errado, o erro tratado está mandando um arquivo HTML, invés de somente uma mensagem de texto:

![image](https://github.com/DOCQC/REPS-BACKEND/assets/62814287/02e7726d-ed7d-4c64-8f58-5c541eb08a78)

2023-11-23 23:10 UTC, SaldanhaElisson commented on src/routers/userTypeRouter.js
> +    userTypeErrorHandler.exists(false),
Por que foi inserido um atributo false como parâmetro ?

2023-11-23 23:10 UTC, SaldanhaElisson commented on src/services/userService.js
> +            user_type_id: data["user_type_id"],
A estrutura para relacionar a uma tabela está errada, deve seguir o padrão utilizando o atributo ```connect``` conforme a imagem abaixo da documentação:


![image](https://github.com/DOCQC/REPS-BACKEND/assets/62814287/a39f0191-cb30-48ea-a722-1e057e55c9a8)

2023-11-23 23:21 UTC, Wilker345 commented on src/routers/userTypeRouter.js
> +    userTypeErrorHandler.exists(false),
define se o id está sendo passado como atributo no json

2023-11-23 23:21 UTC, Wilker345 commented on src/middlewares/exceptions/errorHandler.js
migrate prisma desatualizada

2023-11-24 18:14 UTC, SaldanhaElisson approved these changes

2023-11-24 18:15 UTC, merged