Doc012
DOCQC/REPS-BACKEND pull request #19
Opened 2023-11-27 16:24 UTC by SaldanhaElisson

2023-11-27 17:03 UTC, Wilker345 requested changes

2023-11-27 17:03 UTC, Wilker345 commented on src/middlewares/json/schemas/enterpriseSchema.js
> +            // "patterm": "^(\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}|\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2})$"
Não entendi pq ficou como inteiro

2023-11-27 17:03 UTC, Wilker345 commented on src/services/enterpriseService.js
> +                        connect: {id: data["user_type_id"]}
o tipo de usuário empresa não vai ser uma entidade única e da carga inicial do sistema?

2023-11-27 17:03 UTC, Wilker345 commented on src/middlewares/json/schemas/enterpriseSchema.js
> +            "type": "integer"
é necessário?

2023-11-27 17:13 UTC, Wilker345 requested changes

2023-11-27 17:13 UTC, Wilker345 commented on src/controllers/enterpriseController.js
> +        }
Adiciona o parametro verbose que chegamos a comentar, tem um exemplo na branch de professores. É basicamente pro findAll ser mais eficiente caso não seja necessário os dados da entidade usuário

2023-11-27 17:13 UTC, Wilker345 commented on src/services/enterpriseService.js
> +            cnpj:  String(data["cnpj"]),
CNPJ deve ter uma validação de expressão regular

2023-11-27 17:13 UTC, Wilker345 commented on src/services/enterpriseService.js
> +            cnpj:  String(data["cnpj"]),
mesma coisa do comentário acima

2023-11-27 17:34 UTC, SaldanhaElisson commented on src/services/enterpriseService.js
> +                        connect: {id: data["user_type_id"]}
Como assim ?

2023-11-27 17:34 UTC, SaldanhaElisson commented on src/middlewares/json/schemas/enterpriseSchema.js
> +            // "patterm": "^(\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}|\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2})$"
O number aceita números float

2023-11-27 17:36 UTC, SaldanhaElisson commented on src/middlewares/json/schemas/enterpriseSchema.js
> +            // "patterm": "^(\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}|\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2})$"
![image](https://github.com/DOCQC/REPS-BACKEND/assets/62814287/786ff166-3f3e-4138-b834-bcd7f433bbb6)

2023-11-27 17:54 UTC, Wilker345 commented on src/middlewares/json/schemas/enterpriseSchema.js
> +            // "patterm": "^(\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}|\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2})$"
mas ao passar como inteiro tu permite um número inválido de cnpj. tem que ser string com uma regex que limite à digitos e que tenha o tamanho fixo de 14

2023-11-27 22:49 UTC, Wilker345 requested changes

2023-11-27 22:49 UTC, Wilker345 commented on src/middlewares/exceptions/enterpriseErrorHandler.js
> +    const NotFoundInDelteOrPut = err.code == "P2025" && (req.route.methods.delete || req.route.methods.put)
typo. NotFoundInDeleteOrPut

2023-11-27 22:49 UTC, Wilker345 commented on src/middlewares/exceptions/enterpriseErrorHandler.js
> +    if(NotFoundInDelteOrPut){
mesma coisa acima

2023-11-27 22:49 UTC, Wilker345 commented on src/middlewares/exceptions/enterpriseErrorHandler.js
> +        serviceError.message = "Empresa não encontrado"
não encontrada*. Ou então em inglês como tava o resto das mensagens, enfim temos que padronizar pra um ou outro

2023-11-27 22:49 UTC, Wilker345 commented on src/services/enterpriseService.js
> +    const ENTERPRISE = Number(process.env.ROLE_ENTERPRISE)
pode colocar uma adição no readme.md a respeito?

2023-11-27 22:51 UTC, SaldanhaElisson commented on src/services/enterpriseService.js
> +    const ENTERPRISE = Number(process.env.ROLE_ENTERPRISE)
Beleza

2023-11-28 12:46 UTC, Wilker345 approved these changes

2023-11-28 12:48 UTC, merged