DOCB004  - Pull requeste criando schemas do banco de dados
DOCQC/REPS-BACKEND pull request #4
Opened 2023-11-14 18:04 UTC by SaldanhaElisson

2023-11-14 23:50 UTC, Wilker345 requested changes

2023-11-14 23:50 UTC, Wilker345 commented on package.json
> +  "description": "- Node v18.17 - Yarn Package Manager - Express - JWT - Prisma - MongoDB -a",
Você desfez a correção anterior. Remova o yarn, mongoDB e o typo "-a"

2023-11-14 23:50 UTC, Wilker345 commented on prisma/schema.prisma
> +  @@map("type_user")
user_type?

2023-11-14 23:50 UTC, Wilker345 commented on prisma/schema.prisma
> +  @@map("users")
As tabelas serão no plural ou no singular? Esta é a única  que foi escrita como plural

2023-11-15 17:24 UTC, SaldanhaElisson commented on prisma/schema.prisma
> +  @@map("users")
As tabelas, segundo o professor de banco de dados, devem ser escritas no singular e tals

2023-11-15 18:49 UTC, Wilker345 approved these changes

2023-11-15 18:50 UTC, merged